version: "3.7"
services:
    postgres_db:
        image: postgres:latest
        container_name: postgres_db
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: movie_db
        ports:
            - "5433:5432"
        restart: unless-stopped
        volumes: 
            - pg_data:/var/lib/postgresql/pg_data
volumes: 
    pg_data:
        